### ISSUE TITLE
/slash command not valid

### ISSUE THREAD

**Issue by the-machine-preacher** [ErikKalkoken/slack-demo-heroku#1]
I followed the instructions on your GitHub page, managed to setup the app, deploy it to Heroku and distribute it (which is a good start as I wasn't able to do it before), but the actual commands don't work.

Created a new /slash (/gm) command and linked it as suggested but it does not return "Hi " + user_name + "! How is it going?" as expected when used in the Slack client. It states that the new slash command I created is not valid. Is there something I'm missing?

Your solution is very clever BTW :)

**Comment by ErikKalkoken** [comment]
Hey! 
If Slack does not recognize the new slash command than its not not properly installed on that workspace. Did you maybe create the slash command after the distribution/installation? that would not work. In any case I would suggest to try to add the Slack app again to your workspace. If the installation again works fine, but the slash command still not works then I would check the application log on Heroku next for any errors.

**Comment by the-machine-preacher** [comment]
Yes, I did add the slash command after installing the bot. Will reinstall the bot again and see. Thank you. :)

**Comment by ErikKalkoken** [comment]
Ah, that explains it! Please let me know how it goes and if you need anything else.

**Comment by the-machine-preacher** [comment]
Hey there!

So I re-installed the bot but I keep getting this error in the heroku logs. Its repeatedly states that `tokens.json` file is missing despite me including the file in the directory and adding everything to git and pushing to Heroku:

```
2019-07-30T11:49:15.000000+00:00 app[api]: Build succeeded
2019-07-30T11:50:28.169458+00:00 app[web.1]: WARN: failed to read from tokens.json:  [Errno 2] No such file or directory: 'tokens.json'
2019-07-30T11:50:28.170781+00:00 app[web.1]: 10.61.238.204 - - [30/Jul/2019:11:50:28 +0000] "POST /slash HTTP/1.1" 200 35 "-" "Slackbot 1.0 (+https://api.slack.com/robots)"
2019-07-30T11:50:28.171403+00:00 heroku[router]: at=info method=POST path="/slash" host=virtual-dm.herokuapp.com request_id=bfd6eaa1-3417-4c8a-ae3c-5dfc85c888e0 fwd="54.84.114.171" dyno=web.1 connect=0ms service=4ms status=200 bytes=195 protocol=https
2019-07-30T11:53:38.404588+00:00 app[web.1]: WARN: failed to read from tokens.json:  [Errno 2] No such file or directory: 'tokens.json'
2019-07-30T11:53:38.410732+00:00 app[web.1]: 10.37.197.143 - - [30/Jul/2019:11:53:38 +0000] "POST /slash HTTP/1.1" 200 35 "-" "Slackbot 1.0 (+https://api.slack.com/robots)"
2019-07-30T11:53:38.410744+00:00 heroku[router]: at=info method=POST path="/slash" host=virtual-dm.herokuapp.com request_id=7292fd4a-e649-4860-8cbc-a9e8bbb9ad60 fwd="34.227.78.81" dyno=web.1 connect=1ms service=11ms status=200 bytes=195 protocol=https
```
The `tokens.json` file exists in the directory, but it repeatedly states that it isn't.

**Comment by ErikKalkoken** [comment]
You do not need to (and should not) deploy that file. Its created dynamically by the app in the Heroku dyno and it includes sensitive data that should never be pushed to any public repo. Its why I excluded it from the git in `.gitignore'. 

So its normal that the file does not exist when you first deploy your app to Heroku and you get the warning. The warning should go away once you have installed your app to at least one workspace. Because then the app should have created it.

Btw. As mentioned in the readme the tokens.json file is just a placeholder for a real storage solution like a database.

**Comment by the-machine-preacher** [comment]
The Slack client actually states that "This app is not properly installed" whereas the log files state that the app is unable to detect the `tokens.json` file. I'll keep trying anyway. Could you think of anything in your `app.py` that you'd change? 

One thing I thought of was that I have not added a new web hook to the workspace...

**Comment by ErikKalkoken** [comment]
you are right. looks like the `tokens.json` only has a limited lifetime on the server. My current assumption is that is is removed once the dyno goes to sleep after 30 mins. Let me look into this in more detail. But if we can not make this file persistent then the only other solution would be to use a database for storing the tokens.

**Comment by ErikKalkoken** [comment]
As a "workaround" you can reinstall your app to the workplace. Then it will work again for some time.

**Comment by the-machine-preacher** [comment]
Problem is I've reinstalled it multiple times, it doesn't even work once...

**Comment by ErikKalkoken** [comment]
It works fine in my installation, at least initially. 
Sorry it does not work for you. This is my first Heroku app, so I was not aware that files are not persistent ;-)
Will try to find a solution and will post it here as soon as I does.

**Comment by the-machine-preacher** [comment]
I made another workspace and a fresh install and it worked! I'm not sure why. The bot returns a response only visible to me - is that the same for you?

**Comment by ErikKalkoken** [comment]
awesome. yes, the response will only be visible to the user that issued the slash command.
Still it seams that the tokens file vanishes over time. Need to look into that.

**Comment by the-machine-preacher** [comment]
I'm going to try adopt it to the slackbot now.

**Comment by the-machine-preacher** [comment]
BTW, could the bot not working have anything to do with me changing the name of the folder "slack-demo-heroku"? I cloned the project to my drive, changed its name then followed your instructions. I did not think that changing the name of the folder on my drive would matter, as long as the heroku app and git repository were appropriately named.

**Comment by ErikKalkoken** [comment]
I agree. the name of the git repo should not make any difference.

**Comment by the-machine-preacher** [comment]
Sorry, just one more question - could I now start using `git add.`, `git commit "message"` and `git push heroku master` as I usually do to update my projects on Heroku?

**Comment by ErikKalkoken** [comment]
np.
you sure can. and that is how its meant to work.
however keep in mind that I plan to make changes to my repo to fix the issue with tokens file. you will probably have to merge them manually if you diverge to far from the original.

**Comment by the-machine-preacher** [comment]
Will do! Thank you!

**Comment by ErikKalkoken** [comment]
Here the official explanation why the tokens file vanishes after some time. My assumption was correct.
https://help.heroku.com/K1PPS2WM/why-are-my-file-uploads-missing-deleted

**Comment by ErikKalkoken** [comment]
Btw. If in case you have a simple app that does not need to access the web API then this solution will work. You can just remove whole tokens storage.

**Comment by the-machine-preacher** [comment]
You’re right. The bot stopped working once the dyno went to sleep. The document you linked had something about  “Heroku Postgres” to store info. 

Another thing - my discord bots store user data in json and text files and they store them permanently as they run of worker dynos - which don’t go to sleep.

A simpler work around is to keep pinging the bot with the New Relic addon so it doesn’t sleep.

**Comment by ErikKalkoken** [comment]
Alright. I replaced the file based storage solution with a DB. Its using the standard Heroku PostgreSQL that is also available on the free tier. 
All the code handling the team tokens incl. SQLs are now part of a class and we also have a nice unit test for that.
Please check it out and let me know if you have any issues.

**Comment by the-machine-preacher** [comment]
Will check it out and let you know!

**Comment by ErikKalkoken** [comment]
My new Heroku Slack app using PostgreSQL is still working normally after a couple days, which proves that the new approach is working. I will therefore close this issue. 

If you still have questions or encounter other problems please feel free to open a new issue.

**Comment by dragonmaster784** [comment]
Is there anyway to completely turn off slash commands in Slack?
I am trying to make a regex joke (using a pattern) and I keep getting the stupid error message.
