### ISSUE TITLE
Easy way to connect this to python slackbot?

### ISSUE THREAD

**Issue by the-machine-preacher** [ErikKalkoken/slack-demo-heroku#3]
I setup the bot as you suggested and setup a few slash commands, but I am unable to get it to respond within threads. Connecting this to slackbot (https://github.com/lins05/slackbot) would give it that capability (which incidentally, I think you created the function to respond within threads?!)

Is there an easy way to connect this to Python slackbot ? That is, is it possible to create a function decorated by `slackbot.bot.respond_to` or `slackbot.bot.listen_to` to have the bot respond to commands?

If not, is there any way to get the bot to respond within threads?

**Comment by ErikKalkoken** [comment]
No. Slackbot uses are very different architecture, so trying to combine them does not make much sense. But I made a Slackbot example. Feel free to use it: https://github.com/ErikKalkoken/slackbot-example

**Comment by ErikKalkoken** [comment]
What do you mean by "get it to respond within threads"? In general this app 
should work just fine with threads.

**Comment by the-machine-preacher** [comment]
Let me elaborate:

I started a new message in the #general channel, then opted to start a new thread. You can do that by selecting the message and clicking the ‘start a thread’ option. Within the thread I attempted to issue a /slash command to my bot, but it didn’t work, the following error was returned:

“This slash command is not supported in threads. Sorry!”

How do I issue commands within threads?

**Comment by ErikKalkoken** [comment]
Ah you meant Slack threads, not Python threads!
No you can't. slash command do not work in threads. That has nothing to do with this app.
if you want an app to respond within threads you can do that with Slack events or by using the RTM API.

**Comment by the-machine-preacher** [comment]
Hmm, that is disappointing. I am currently using a Slack bot that I created and responds within threads. It runs on Heroku, the only problem is that it cannot be invited to another workspace (I cannot make it available for others to use).

**Comment by ErikKalkoken** [comment]
You mean a slackbot based on this: https://github.com/lins05/slackbot
Yes it uses RTM API, so it will work in threads.
It should be possible to use your slackbot with other workspace, however  I personally have limited experience with RTM apps, so best to ask on the github mentioned above.

**Comment by ErikKalkoken** [comment]
Here is how it works in general: https://stackoverflow.com/questions/48972465/how-can-i-share-my-slack-app-between-my-workspaces
