### ISSUE TITLE
How to access text content of s message?

### ISSUE THREAD

**Issue by the-machine-preacher** [ErikKalkoken/slack-demo-heroku#4]
Hey there, I thought I could get you here! Using Python Slackbot framework I did this:

```
from slackbot.bot import respond_to

@respond_to('Give me (.*)')
def giveme(message, something):
    message.reply('Here is {}'.format(something))
```
But how do I access the text content of the message itself?

**Comment by ErikKalkoken** [comment]
In general I am always happy to help, but this question does not appear to relate to my app. Would suggest to either open an issue with the guys that made slackbot.bot or on stackoverflow.
